version: '3.3'
services:
  app:
    build:
      context: .
    ports:
      - '3000:3000'
  postgres:
    image: 'postgres:11.7-alpine'
    environment:
      POSTGRES_DB: slaters
      POSTGRES_PASSWORD: slaters
      POSTGRES_USER: slaters
    restart: always
